Update piepeline.yml

diff --git a/.github/workflows/piepeline.yml b/.github/workflows/piepeline.yml
--- a/.github/workflows/piepeline.yml
+++ b/.github/workflows/piepeline.yml
@@ -13,10 +13,10 @@ on:
         options:
           - prod
           - INT
-          
+
 permissions:
   contents: write
-  
+
 jobs:
   update-password:
     runs-on: ubuntu-latest
@@ -45,7 +45,7 @@ jobs:
 
           clusters=("cluster1" "cluster2" "cluster3")
           for cluster in "${clusters[@]}"; do
-            xml_file="./$cluster.xml"
+            xml_file="./${{ github.event.inputs.environment }}/$cluster.xml"
             temp_xml_file="./${{ github.event.inputs.environment }}/$cluster.tmp.xml"
             echo "Creating/Updating temporary file $temp_xml_file"
             
@@ -61,8 +61,24 @@ jobs:
             fi
 
             echo "Renaming $temp_xml_file to $xml_file"
-            mv "$temp_xml_file" "$xml_file"
+            mv "$temp_xml_file" "$xml_file" && echo "Renamed successfully" || echo "Renaming failed"
           done
+
+      - name: Debug Temporary XML File Content
+        run: |
+          for cluster in cluster1 cluster2 cluster3; do
+            temp_file="./${{ github.event.inputs.environment }}/$cluster.tmp.xml"
+            if [ -f "$temp_file" ]; then
+              echo "Contents of $temp_file:"
+              cat "$temp_file"
+            else
+              echo "$temp_file does not exist."
+            fi
+          done
+
+      - name: List XML Files
+        run: |
+          ls -l "./${{ github.event.inputs.environment }}"
 
       - name: Commit changes to SCM
         run: |
